Models/Bowler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; }

        [Required(ErrorMessage = "Last name is required.")]
        public string BowlerLastName { get; set; }

        [Required(ErrorMessage = "First name is required.")]
        public string BowlerFirstName { get; set; }

        [MaxLength(1)]
        public string BowlerMiddleInit { get; set; }
        public string BowlerAddress { get; set; }
        public string BowlerCity { get; set; }

        [MaxLength(2)]
        public string BowlerState { get; set; }
        public string BowlerZip { get; set; }

        public string BowlerPhoneNumber { get; set; }

        [Required(ErrorMessage = "Team name is required.")]
        public int TeamID { get; set; }

        //Build Foreign Key Relationship
        public Team Team { get; set; }
        //public Team TeamName { get; set; }

    }

}

Models/BowlingLeagueDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class BowlingLeagueDbContext : DbContext
    {
        public BowlingLeagueDbContext(DbContextOptions<BowlingLeagueDbContext> options): base (options)
        {

        }

        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }

     
    }
}

Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Models
{
    public class Team
    {
        
        [Key]
        [Required]
        public int TeamID { get; set; }

        [Required(ErrorMessage = "Team name is required.")]
        public string TeamName { get; set; }
        public int CaptainID { get; set; }
        
    }
}

Components/TypesViewComponent.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission13.Models;

namespace Mission13.Components
{
    public class TypesViewComponent : ViewComponent
    {
        // bowlingleaguecontext
        private BowlingLeagueDbContext bowler { get; set; }

        // constructor
        public TypesViewComponent(BowlingLeagueDbContext temp)
        {
            bowler = temp;
        }

        // invoke
        public IViewComponentResult Invoke()
        {
            // route data of teamName --> assign in ViewBag.SelectedTeam
            ViewBag.SelectedTeam = RouteData?.Values["teamName"] ?? "";

            // get team names
            var teams = bowler.Bowlers
                .Select(x => x.Team.TeamName)
                .Distinct()
                .OrderBy(x => x);

            return View(teams);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Mission13.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Mission13.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;
        private BowlingLeagueDbContext bowler { get; set; }

        //contstructor
        public HomeController(BowlingLeagueDbContext someName)
        {
            bowler = someName;
        }


        public IActionResult Index(string teamName)
        {
            
            HttpContext.Session.Remove("id");

            // assign teamName for ViewBag.TeamName
            ViewBag.TeamName = teamName ?? "Home";

            // get record of bowlers from teamName
            var record = bowler.Bowlers
                .Include(x => x.Team)
                .Where(x => x.Team.TeamName == teamName || teamName == null)
                .ToList();
            return View(record);
        }

        //get and post methods for the bowler submission form
        [HttpGet]
        public IActionResult BowlerSubmission()
        {
            ViewBag.Teams = bowler.Teams.ToList();

            return View();
        }

        //make sure to add and save changes to the bowlers in the  database
        [HttpPost]
        public IActionResult BowlerSubmission(Bowler b)
        {
            if (ModelState.IsValid)
            {
                bowler.Add(b);
                bowler.SaveChanges();

                return View("Confirmation", b);
            }
            else //validation
            {
                ViewBag.Teams = bowler.Teams.ToList();

                return View();
            }

        }

        //edit record
        [HttpGet]
        public IActionResult Edit(int bowlerid)
        {

            ViewBag.Teams = bowler.Teams.ToList();

            var record = bowler.Bowlers.Single(x => x.BowlerID == bowlerid);

            return View("BowlerSubmission", record);
        }


        [HttpPost]
        public IActionResult Edit(Bowler blah)
        {
            bowler.Update(blah);
            bowler.SaveChanges();

            return RedirectToAction("Index");
        }

        //delete record
        [HttpGet]
        public IActionResult Delete(int bowlerid)
        {
            var blah = bowler.Bowlers.Single(x => x.BowlerID == bowlerid);

            return View(blah);
        }

        [HttpPost]
        public IActionResult Delete(Bowler br)
        {
            
            //blahContext.Bowlers.Remove(br);
            foreach (var tatertot in bowler.Bowlers)
            {
                if(tatertot.BowlerID == br.BowlerID)
                {
                    bowler.Bowlers.Remove(tatertot);
                }
            }
            bowler.SaveChanges();

            return RedirectToAction("Index", new { teamName = "" });
        }

    }

}

Views/Home/BowlerSubmission.cshtml
@{
    ViewData["Title"] = "Bowler Submission";
}

@model Mission13.Models.Bowler

@*Form for bowler submission*@
<div>
    <form method="post">

        <div asp-validation-summary="All"></div>

        <label asp-for="BowlerFirstName">First Name:</label>
        <input asp-for="BowlerFirstName" /><br />

        <label asp-for="BowlerMiddleInit">Middle Initial:</label>
        <input asp-for="BowlerMiddleInit" /><br />

        <label asp-for="BowlerLastName">Last Name:</label>
        <input asp-for="BowlerLastName" /><br />

        <label asp-for="BowlerAddress">Address:</label>
        <input asp-for="BowlerAddress" /><br />

        <label asp-for="BowlerCity">City:</label>
        <input asp-for="BowlerCity" /><br />

        <label asp-for="BowlerState">State:</label>
        <input asp-for="BowlerState" /><br />

        <label asp-for="BowlerZip">Zip:</label>
        <input asp-for="BowlerZip" /><br />

        <label asp-for="BowlerPhoneNumber">Phone Number:</label>
        <input asp-for="BowlerPhoneNumber" /><br />

        <label asp-for="TeamID">Team:</label>
        <select asp-for="TeamID">
            <option value="">Select a Team</option>
            @foreach (Team t in ViewBag.Teams)
            {
                <option value="@t.TeamID">@t.TeamName</option>
            }
        </select><br />

        @*<input type="hidden" asp-for="BowlerID" />*@

        <button class="btn btn-primary" type="submit">Submit Bowler</button>
        @if (ViewBag.New == false)
        {
            <input type="hidden" asp-for="BowlerID" />
        }

    </form>
</div>

Views/Home/Confirmation.cshtml
@{
    ViewData["Title"] = "Bowler Submitted";
}

@model Mission13.Models.Bowler

@*awesome confirmation message*@

<h2>The fantastic bowler, @Model.BowlerFirstName @Model.BowlerLastName, has been submitted!</h2>

Views/Home/Delete.cshtml
@{
    ViewData["Title"] = "Delete Bowler";
}

@model Bowler

@*delete confirmation page*@

<h2>Confirm Deletion</h2>
<h3>Are you sure you want to delete @Model.BowlerFirstName @Model.BowlerLastName?</h3>

<form method="post" asp-controller="Home" asp-action="Delete">
    <button type="submit">Delete</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-outline-primary">Cancel</a>

    <input type="hidden" asp-for="BowlerID" />
    <input type="hidden" asp-for="TeamID" />
    @*<input type="hidden" asp-for="Team" />*@
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Bowler>

<h1>@ViewBag.TeamName</h1>

<h2>Bowler Info</h2>

<br />
<br />
<table class="table table-sm table-striped table-bordered">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Middle Init</th>
            <th>Last Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Phone Number</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var b in Model)
        {

            <tr>
                <td>@b.BowlerFirstName</td>
                <td>@b.BowlerMiddleInit</td>
                <td>@b.BowlerLastName</td>
                <td>@b.BowlerAddress</td>
                <td>@b.BowlerCity</td>
                <td>@b.BowlerState</td>
                <td>@b.BowlerZip</td>
                <td>@b.BowlerPhoneNumber</td>
                <td>
                    <a class="btn btn-success" asp-action="Edit" asp-route-bowlerId="@b.BowlerID">Edit</a>
                </td>
                <td>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-bowlerId="@b.BowlerID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/Components/Types/Default.cshtml
@{
}

@model IEnumerable<string>


<div class="d-grid gap-2" id="types">
    <a asp-controller="Home" asp-action="Index" asp-route-teamName=""
       class="btn @(ViewBag.SelectedTeam == "" ? "btn-primary" :  "btn-outline-secondary")">Home</a>
    <br />

    @foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-teamName="@t"
           class="btn @(ViewBag.SelectedTeam == t ? "btn-primary" :  "btn-outline-secondary")">@t</a>
        <br />
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission13</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mission13</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="BowlerSubmission">Add Bowler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @*team name filter*@
    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>
        
        <div class="col-9">
            @RenderBody()
        </div>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>